services:
  frontalface:
    build: ./FaceOrientationBackend
    image: mayankjonwal02/iitj_face_verification_backend-frontalface
    container_name: frontalface
    ports:
      - "8001:8001"
    networks:
      - backend_network

  web:
    build: ./libraryproject
    image: mayankjonwal02/iitj_face_verification_backend-web
    container_name: web
    command: ["sh", "-c", "python manage.py migrate && gunicorn libraryproject.wsgi:application --bind 0.0.0.0:8000"]
    volumes:
      - ./libraryproject:/app
    depends_on:
      - frontalface
    environment:
      - DB_HOST=db  # If DB_HOST is still pointing to a database, ensure it's properly configured or remove this if unnecessary
      - DB_NAME=UserDatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8003:8003"
    depends_on:
      - web
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge
